### ISSUE TITLE
VerificationException: Operation could destabilize the runtime. Silverlight 5.0

### ISSUE THREAD

**Issue by ykhenokh** [lunet-io/markdig#131]
installed Markdig 0.12.3 from NuGet into Silverlight project. packages.config:

 &lt;package id="Markdig" version="0.12.3" targetFramework="sl50" /&gt;

Called Markdown.ToHtml("test") from Silverlight 5.0 app and got this back:

{System.Security.VerificationException: Operation could destabilize the runtime.
   at Markdig.Helpers.CharacterMap`1.IndexOfOpeningCharacter(String text, Int32 start, Int32 end)
   at Markdig.Parsers.ParserList`2.IndexOfOpeningCharacter(String text, Int32 start, Int32 end)
   at Markdig.Parsers.Inlines.LiteralInlineParser.Match(InlineProcessor processor, StringSlice& slice)
   at Markdig.Parsers.InlineProcessor.ProcessInlineLeaf(LeafBlock leafBlock)
   at Markdig.Parsers.MarkdownParser.ProcessInlines()
   at Markdig.Parsers.MarkdownParser.Parse()
   at Markdig.Parsers.MarkdownParser.Parse(String text, MarkdownPipeline pipeline)
   at Markdig.Markdown.Parse(String markdown, MarkdownPipeline pipeline)
   at Markdig.Markdown.ToHtml(String markdown, TextWriter writer, MarkdownPipeline pipeline)
   at Markdig.Markdown.ToHtml(String markdown, MarkdownPipeline pipeline)
   .....

**Comment by xoofx** [comment]
Wow, you are using Markdig with Silverlight...

Well, this method is using unsafe and it appears that [Silverlight doesn't support this well](http://cureos.blogspot.fr/2011/09/unsafe-support-in-silverlight-5.html)

Will check assembly .NET fwk targets and how to make nuget resolution playing well for Silverlight...

**Comment by xoofx** [comment]
Should be fixed by a7786d9 and part of up-coming 0.12.4
